### ISSUE TITLE
Do you plan on releasing the code for the control experiments?

### ISSUE THREAD

**Issue by llucid-97** [JannerM/gamma-models#2]
Hi, great stuff, and thanks for open sourcing this.
Do you plan on releasing the code for the value estimation or control aspects of this?

**Comment by jannerm** [comment]
The code for value estimation is already in the repo. Check out the last cell in the notebooks with:
```
visualize_values(prob_fn, n_steps=20)
```

We don't have plans to release the control code in the short term.
